export const LOAD_PASSENGERS = 'LOAD_PASSENGERS';
export const LOAD_PASSENGERS_SUCCESS = 'LOAD_PASSENGERS_SUCCESS';
export const CREATE_PASSENGER = 'CREATE_PASSENGER';
export const ADD_PASSENGERS = 'ADD_PASSENGERS';
export const UPDATE_PASSENGER = 'UPDATE_PASSENGER';
export const UPDATE_PASSENGER_SUCCESS = 'UPDATE_PASSENGER_SUCCESS';
